const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923186587796" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923186587796";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923186587796,923186587796";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923186587796";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923186587796,923186587796";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "NOBITA",
  ownername:process.env.OWNER_NAME|| "NOBITA",

  sessionName:process.env.SESSION_ID || "SUHAIL_22_02_08_29_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDAsXG4gICAgICAgIDE1NixcbiAgICAgICAgMixcbiAgICAgICAgNTksXG4gICAgICAgIDQxLFxuICAgICAgICA3OSxcbiAgICAgICAgMTM5LFxuICAgICAgICAyNDcsXG4gICAgICAgIDkxLFxuICAgICAgICAxNSxcbiAgICAgICAgMTc5LFxuICAgICAgICA3NixcbiAgICAgICAgMTc2LFxuICAgICAgICAxNDMsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTgyLFxuICAgICAgICA5MCxcbiAgICAgICAgMjUwLFxuICAgICAgICAxNjMsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMjA4LFxuICAgICAgICAyMzMsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjIsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTg3LFxuICAgICAgICA5LFxuICAgICAgICA2LFxuICAgICAgICA0MixcbiAgICAgICAgOTksXG4gICAgICAgIDIxMSxcbiAgICAgICAgNzFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA5LFxuICAgICAgICAxNTYsXG4gICAgICAgIDEsXG4gICAgICAgIDE3NyxcbiAgICAgICAgODUsXG4gICAgICAgIDk5LFxuICAgICAgICA4NixcbiAgICAgICAgNjksXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMzcsXG4gICAgICAgIDY4LFxuICAgICAgICAxMTEsXG4gICAgICAgIDY3LFxuICAgICAgICAxMzEsXG4gICAgICAgIDI0NyxcbiAgICAgICAgNjgsXG4gICAgICAgIDgxLFxuICAgICAgICAxNDYsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTkxLFxuICAgICAgICA2MyxcbiAgICAgICAgNzUsXG4gICAgICAgIDE4MSxcbiAgICAgICAgODQsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTM3LFxuICAgICAgICAyMjAsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjA3LFxuICAgICAgICA3NixcbiAgICAgICAgMTE0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAwLFxuICAgICAgICAyMTMsXG4gICAgICAgIDMwLFxuICAgICAgICAyNCxcbiAgICAgICAgNTgsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMSxcbiAgICAgICAgMTY4LFxuICAgICAgICAyMzEsXG4gICAgICAgIDE3NixcbiAgICAgICAgNTgsXG4gICAgICAgIDQyLFxuICAgICAgICAxNTMsXG4gICAgICAgIDE4MSxcbiAgICAgICAgNjQsXG4gICAgICAgIDQsXG4gICAgICAgIDE5MixcbiAgICAgICAgNTIsXG4gICAgICAgIDExMixcbiAgICAgICAgMTA1LFxuICAgICAgICA4MSxcbiAgICAgICAgNTgsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTY5LFxuICAgICAgICAxNDgsXG4gICAgICAgIDgzLFxuICAgICAgICAyNDgsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTY1LFxuICAgICAgICAyLFxuICAgICAgICAxNTksXG4gICAgICAgIDY2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1MixcbiAgICAgICAgMTA1LFxuICAgICAgICAyMzQsXG4gICAgICAgIDc2LFxuICAgICAgICAyNDgsXG4gICAgICAgIDUzLFxuICAgICAgICAyMDgsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMjU0LFxuICAgICAgICAxMzMsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTU4LFxuICAgICAgICAxMzksXG4gICAgICAgIDE3LFxuICAgICAgICAxNDAsXG4gICAgICAgIDg5LFxuICAgICAgICAxOTMsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMjQ3LFxuICAgICAgICAyMzgsXG4gICAgICAgIDEwLFxuICAgICAgICAyNTIsXG4gICAgICAgIDkxLFxuICAgICAgICA0OCxcbiAgICAgICAgMjEwLFxuICAgICAgICAxOTIsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMzksXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTYsXG4gICAgICAgIDE3MCxcbiAgICAgICAgNDVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDMyLFxuICAgICAgICA4MyxcbiAgICAgICAgMTYzLFxuICAgICAgICAxNDMsXG4gICAgICAgIDQzLFxuICAgICAgICA2OSxcbiAgICAgICAgMTE3LFxuICAgICAgICAyMjgsXG4gICAgICAgIDc1LFxuICAgICAgICAyMixcbiAgICAgICAgMTM1LFxuICAgICAgICAxMjUsXG4gICAgICAgIDMwLFxuICAgICAgICAxMzQsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMjAwLFxuICAgICAgICAyNDksXG4gICAgICAgIDEyOCxcbiAgICAgICAgOTksXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTI5LFxuICAgICAgICA0MixcbiAgICAgICAgMTQxLFxuICAgICAgICAxODcsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTUzLFxuICAgICAgICA0OCxcbiAgICAgICAgMTYxLFxuICAgICAgICAxNDksXG4gICAgICAgIDE5MCxcbiAgICAgICAgMjAxLFxuICAgICAgICAxMDdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTg0LFxuICAgICAgICAxNDgsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTk1LFxuICAgICAgICAyMDIsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTA5LFxuICAgICAgICA3NSxcbiAgICAgICAgOTAsXG4gICAgICAgIDI5LFxuICAgICAgICA3MixcbiAgICAgICAgMjI3LFxuICAgICAgICAyMTQsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMyxcbiAgICAgICAgMjI3LFxuICAgICAgICA2NCxcbiAgICAgICAgNixcbiAgICAgICAgMjQ0LFxuICAgICAgICAyMzQsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTY0LFxuICAgICAgICA2NSxcbiAgICAgICAgNjYsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMjA3LFxuICAgICAgICAzOSxcbiAgICAgICAgMTExLFxuICAgICAgICAyMDksXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTgzLFxuICAgICAgICAxMDNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDMsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgNDEsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAxMDNcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDMwLFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDE2MSxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICA3MixcbiAgICAgICAgICA1OCxcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDExNixcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDJcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4OSxcbiAgICAgICAgMTk4LFxuICAgICAgICA2OSxcbiAgICAgICAgMTk1LFxuICAgICAgICA2NCxcbiAgICAgICAgMTU1LFxuICAgICAgICAxOTcsXG4gICAgICAgIDk0LFxuICAgICAgICAyMjUsXG4gICAgICAgIDIxNCxcbiAgICAgICAgNixcbiAgICAgICAgMjQ0LFxuICAgICAgICAxMzcsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMjYsXG4gICAgICAgIDE0NCxcbiAgICAgICAgNixcbiAgICAgICAgMTI2LFxuICAgICAgICAyMDgsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMjI0LFxuICAgICAgICAxNzAsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMTg0LFxuICAgICAgICAxNTAsXG4gICAgICAgIDAsXG4gICAgICAgIDE0OCxcbiAgICAgICAgODYsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMDgsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTcsXG4gICAgICAgIDk5LFxuICAgICAgICAxOTQsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNjMsXG4gICAgICAgIDEsXG4gICAgICAgIDYyLFxuICAgICAgICA4OCxcbiAgICAgICAgMjIzLFxuICAgICAgICAyMTYsXG4gICAgICAgIDE4OSxcbiAgICAgICAgNTcsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMTAsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTg2LFxuICAgICAgICAyNDksXG4gICAgICAgIDY4LFxuICAgICAgICAxMzAsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjI1LFxuICAgICAgICAyMzQsXG4gICAgICAgIDE3LFxuICAgICAgICAxMzMsXG4gICAgICAgIDE1MSxcbiAgICAgICAgNDIsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMzcsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTM4XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAyMjMsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiNm92WDlIanMzMU9KUS90N3g4OGtaMzArb1hNNmx4SlB0ZEQ2NVE5dFZsST1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMxODY1ODc3OTZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkI2QTFDMTJDMjQ5NjA0RThBNDhFMThBREM5Q0ZBMEVEXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNDk2ODkzM1xuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJJc2w4OHZTZFNpNm13UXlEbTFSdndBXCIsXG4gIFwicGhvbmVJZFwiOiBcImI5ZjYxYTliLTExYTEtNDA3MS04OWJkLWIyMjAwODJmNmJhNVwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxNDUsXG4gICAgICAxNTUsXG4gICAgICAxNDUsXG4gICAgICAxNjAsXG4gICAgICAyMjgsXG4gICAgICAxMDgsXG4gICAgICA0MixcbiAgICAgIDY5LFxuICAgICAgNzksXG4gICAgICA5OCxcbiAgICAgIDc3LFxuICAgICAgOTYsXG4gICAgICAxNTMsXG4gICAgICAyMTQsXG4gICAgICAxMjAsXG4gICAgICAyNTUsXG4gICAgICAxNzAsXG4gICAgICAyMjMsXG4gICAgICAyNTMsXG4gICAgICAwXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDc2LFxuICAgICAgNjMsXG4gICAgICA0MixcbiAgICAgIDk2LFxuICAgICAgMTA2LFxuICAgICAgMTk1LFxuICAgICAgMjQyLFxuICAgICAgMTAzLFxuICAgICAgMjM3LFxuICAgICAgOTAsXG4gICAgICAxMDksXG4gICAgICAxODMsXG4gICAgICA3NSxcbiAgICAgIDI1LFxuICAgICAgMTE3LFxuICAgICAgMjU1LFxuICAgICAgMTk1LFxuICAgICAgNDgsXG4gICAgICAxNTUsXG4gICAgICAxOThcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiQ0FRQlZOM01cIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzE4NjU4Nzc5Njo0MkBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIuqngcmyxqHGhcmqxq3KjCDJps+FIMmjyozJvuqnglwiLFxuICAgIFwibGlkXCI6IFwiMTcwMTAyNjY2MzUwNzMwOjQyQGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0k3Szc5SUdFTnZmdzdZR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiM1ExOFU1bUY2V1ZZZHdFUnpNbDJTTEFYcmRDYjhIQjVWcFJqdW14TUZHaz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJVc1hDRWRwWTg1NTFLQTB2eDNBbUdLWVpTeVNlQmJCQzhiZkl1dTcxV2ZsVW1hMTN5UlZvZ3ZoK3hFMTdmSUJObXZCSlFZMWF2WWZMdGZQVHlMOEFEdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJ1UjExazBWRkZCSzVid25Wem5iRzR6UERZY1hwQlo5TzNKRndvV00rdkc0ZE40RUhEeWhjUTNqRzNMalN3eUdaUm9wYzZmZ3VlQnhBbnVrZHM4UzFqUT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjMxODY1ODc3OTY6NDJAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAxMzMsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAxMTksXG4gICAgICAgICAgMSxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDExMixcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMTA1XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjQ5Njg5MjgsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFMbEFcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUxsQS5qc29uIjogIntcImtleURhdGFcIjpcImJGc3B5Vk4zYS9NajJaNG01S1ZmcnBDdnVEZHNDMU5GcGUvL2JRdUg2U3M9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTc4NDQwNzMwOSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyNDk2ODkwODA0MlwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
