const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923186587796" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923186587796";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923186587796,923186587796";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923186587796";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923186587796,923186587796";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "NOBITA",
  ownername:process.env.OWNER_NAME|| "NOBITA",

  sessionName:process.env.SESSION_ID || "SUHAIL_17_11_08_29_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMCxcbiAgICAgICAgMjIzLFxuICAgICAgICAxNTIsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTc0LFxuICAgICAgICAxMDQsXG4gICAgICAgIDEyLFxuICAgICAgICAxMDAsXG4gICAgICAgIDIzNCxcbiAgICAgICAgNTQsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTkyLFxuICAgICAgICAxLFxuICAgICAgICA4LFxuICAgICAgICA1MCxcbiAgICAgICAgMTA4LFxuICAgICAgICAyMzgsXG4gICAgICAgIDEwMSxcbiAgICAgICAgNjMsXG4gICAgICAgIDI1MixcbiAgICAgICAgMTk2LFxuICAgICAgICAxMTUsXG4gICAgICAgIDIsXG4gICAgICAgIDYsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTc3LFxuICAgICAgICAxNzIsXG4gICAgICAgIDExNixcbiAgICAgICAgNzYsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTI0LFxuICAgICAgICA5M1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzcsXG4gICAgICAgIDE5MSxcbiAgICAgICAgNCxcbiAgICAgICAgMjI0LFxuICAgICAgICAxODUsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTkwLFxuICAgICAgICAxNCxcbiAgICAgICAgMjEwLFxuICAgICAgICA5NSxcbiAgICAgICAgMjEsXG4gICAgICAgIDE5LFxuICAgICAgICAyMDQsXG4gICAgICAgIDc4LFxuICAgICAgICAyNDQsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTE4LFxuICAgICAgICAyMzYsXG4gICAgICAgIDI0NyxcbiAgICAgICAgNzMsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjA1LFxuICAgICAgICAxODYsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTEsXG4gICAgICAgIDI1MixcbiAgICAgICAgMTA1LFxuICAgICAgICA4MSxcbiAgICAgICAgMjExLFxuICAgICAgICAxNDMsXG4gICAgICAgIDYwLFxuICAgICAgICAzM1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTY4LFxuICAgICAgICA5MCxcbiAgICAgICAgMjAzLFxuICAgICAgICAyNTEsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjIsXG4gICAgICAgIDY3LFxuICAgICAgICAxMjgsXG4gICAgICAgIDIzLFxuICAgICAgICAxOSxcbiAgICAgICAgMjA5LFxuICAgICAgICAxMzgsXG4gICAgICAgIDU5LFxuICAgICAgICAyMDQsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjIyLFxuICAgICAgICAzMSxcbiAgICAgICAgMjE1LFxuICAgICAgICA2LFxuICAgICAgICAwLFxuICAgICAgICAwLFxuICAgICAgICAxMzYsXG4gICAgICAgIDM4LFxuICAgICAgICA5MSxcbiAgICAgICAgNDIsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMTksXG4gICAgICAgIDE4NixcbiAgICAgICAgMjEsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTA2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIxNyxcbiAgICAgICAgMjE0LFxuICAgICAgICAxNjgsXG4gICAgICAgIDg3LFxuICAgICAgICAyOCxcbiAgICAgICAgMjM1LFxuICAgICAgICAxNzMsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTksXG4gICAgICAgIDk4LFxuICAgICAgICAyMDYsXG4gICAgICAgIDIyNSxcbiAgICAgICAgNCxcbiAgICAgICAgNDgsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMzEsXG4gICAgICAgIDYxLFxuICAgICAgICAyNDYsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTc4LFxuICAgICAgICAyMzQsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTk1LFxuICAgICAgICAyMzcsXG4gICAgICAgIDk2LFxuICAgICAgICAxMjIsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjIxLFxuICAgICAgICA0NyxcbiAgICAgICAgMTU1LFxuICAgICAgICAyMDIsXG4gICAgICAgIDYwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2NCxcbiAgICAgICAgMjUwLFxuICAgICAgICAxNTUsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTExLFxuICAgICAgICAyMTIsXG4gICAgICAgIDc5LFxuICAgICAgICA5MyxcbiAgICAgICAgNzcsXG4gICAgICAgIDIxLFxuICAgICAgICAxODMsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTYxLFxuICAgICAgICA0NSxcbiAgICAgICAgMTMxLFxuICAgICAgICAxMzQsXG4gICAgICAgIDY5LFxuICAgICAgICAxMzUsXG4gICAgICAgIDM2LFxuICAgICAgICA0NCxcbiAgICAgICAgMzAsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTUxLFxuICAgICAgICAxMDcsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTgsXG4gICAgICAgIDQ2LFxuICAgICAgICAxNDAsXG4gICAgICAgIDQxLFxuICAgICAgICAyMTEsXG4gICAgICAgIDUzLFxuICAgICAgICA4NlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4NCxcbiAgICAgICAgMTE4LFxuICAgICAgICA4LFxuICAgICAgICAxNDEsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTExLFxuICAgICAgICA5LFxuICAgICAgICAyNTIsXG4gICAgICAgIDc0LFxuICAgICAgICA5OCxcbiAgICAgICAgNjcsXG4gICAgICAgIDEyLFxuICAgICAgICAyMixcbiAgICAgICAgMjA4LFxuICAgICAgICA2MyxcbiAgICAgICAgMjA3LFxuICAgICAgICAxNDYsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMjI2LFxuICAgICAgICA2MixcbiAgICAgICAgMjMxLFxuICAgICAgICAyMTksXG4gICAgICAgIDI0NSxcbiAgICAgICAgOTgsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTQwLFxuICAgICAgICA2MCxcbiAgICAgICAgNjcsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTUyLFxuICAgICAgICAxNDcsXG4gICAgICAgIDg2XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAyNTMsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAyMTksXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAxMSxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDEyNixcbiAgICAgICAgICA3NyxcbiAgICAgICAgICAxMzksXG4gICAgICAgICAgMTk0LFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDY2XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMjAzLFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICA4NyxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICAxMSxcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICA5MCxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgOTRcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNDYsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTQyLFxuICAgICAgICAxMzIsXG4gICAgICAgIDE4LFxuICAgICAgICAxNjIsXG4gICAgICAgIDg1LFxuICAgICAgICAyMjksXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjI5LFxuICAgICAgICAxMzcsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTAwLFxuICAgICAgICA1MyxcbiAgICAgICAgMTksXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTUyLFxuICAgICAgICAyMjAsXG4gICAgICAgIDgyLFxuICAgICAgICA2NCxcbiAgICAgICAgMCxcbiAgICAgICAgMTA5LFxuICAgICAgICAxMSxcbiAgICAgICAgMjA5LFxuICAgICAgICA2MCxcbiAgICAgICAgMTc1LFxuICAgICAgICAyNSxcbiAgICAgICAgNDIsXG4gICAgICAgIDE1MixcbiAgICAgICAgMjAyLFxuICAgICAgICAzNixcbiAgICAgICAgNzksXG4gICAgICAgIDIwOCxcbiAgICAgICAgODgsXG4gICAgICAgIDExMixcbiAgICAgICAgMTQzLFxuICAgICAgICAxMDAsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMjM5LFxuICAgICAgICA5MSxcbiAgICAgICAgNzEsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjM3LFxuICAgICAgICAyNDQsXG4gICAgICAgIDk2LFxuICAgICAgICAyOCxcbiAgICAgICAgMTUsXG4gICAgICAgIDExMCxcbiAgICAgICAgOTYsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMjQzLFxuICAgICAgICA4MyxcbiAgICAgICAgMjA2LFxuICAgICAgICAyMzgsXG4gICAgICAgIDEyOCxcbiAgICAgICAgNDEsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTA3LFxuICAgICAgICAyMDIsXG4gICAgICAgIDM2LFxuICAgICAgICA3MCxcbiAgICAgICAgMjE1LFxuICAgICAgICAxOTYsXG4gICAgICAgIDFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDE5MyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCI2MEFPZlQ1TjNVMVVUSGJmVnR6ekEvdmg1RGVvNk9pR2xVNEhtTVNqUTEwPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzE4NjU4Nzc5NkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNUI0RUQ3ODc1QTYwN0YwQ0UxQUQyMTVBNTlFQzFDODJcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI0OTUxNDY4XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcInc2N1BiS0dlUlFlekJ3bDVFTDRNQ3dcIixcbiAgXCJwaG9uZUlkXCI6IFwiOWE2NTg3OWMtMzM1Yi00OTU1LWFlNGEtNTVjNmFjZGI4OTBjXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDkwLFxuICAgICAgMzYsXG4gICAgICAxNDUsXG4gICAgICAyNDgsXG4gICAgICA1OCxcbiAgICAgIDExMSxcbiAgICAgIDI3LFxuICAgICAgMjM0LFxuICAgICAgMCxcbiAgICAgIDE5NyxcbiAgICAgIDQwLFxuICAgICAgMjE1LFxuICAgICAgODQsXG4gICAgICAxNjEsXG4gICAgICA2NixcbiAgICAgIDE4MCxcbiAgICAgIDEzOCxcbiAgICAgIDExNCxcbiAgICAgIDI1MyxcbiAgICAgIDE1OFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMjksXG4gICAgICAxNzIsXG4gICAgICAyMTMsXG4gICAgICA2OCxcbiAgICAgIDIyMixcbiAgICAgIDY1LFxuICAgICAgMjAwLFxuICAgICAgOTksXG4gICAgICAyMDMsXG4gICAgICAxMjIsXG4gICAgICAxNTEsXG4gICAgICA3MixcbiAgICAgIDIwOSxcbiAgICAgIDgzLFxuICAgICAgMjgsXG4gICAgICAxODIsXG4gICAgICAxMTYsXG4gICAgICA5NSxcbiAgICAgIDE3MyxcbiAgICAgIDg5XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIlg3UlBXOFpRXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5MjMxODY1ODc3OTY6NDFAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCLqp4HJssahxoXJqsatyowgyabPhSDJo8qMyb7qp4JcIixcbiAgICBcImxpZFwiOiBcIjE3MDEwMjY2NjM1MDczMDo0MUBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNJM0s3OUlHRUtQWHdyWUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjNRMThVNW1GNldWWWR3RVJ6TWwyU0xBWHJkQ2I4SEI1VnBSanVteE1GR2s9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiZHN2Y1d2dVhFemtCZm9QMkxnSGdaT0ZxT1ppS0MvSUNnaS9zbEZMWmNDeTNPQmZZdUFwRHNwMkFSTkRkQnBPaFJib2N6Z0psdkRlYTF4Zk1TQnBFRFE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwid3Nwbkt4ekV0bVIwMVdGTzQ5UVpOK3JsV1hDS2RBaVprcnp0NUUra1ZOQk5hRUl6Z0ZTVWhaUFhXbGlkMWpIVWxtNjVnNklFRFA2NG5ITGdWU1BDQnc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTIzMTg2NTg3Nzk2OjQxQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDEsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDEwNVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI0OTUxNDYyLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBTGszXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFMazMuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJQRDR4WEhmWXJVNmpsWWIxK0tvYjVFdm1ra0ZOVWNoQ0JSWXE1N3MwLzRzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE3ODQ0MDczMDUsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjQ4MzIxNzQ3MTVcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
